server:
  port: 8090

spring:
  application:
    name: PEP1
  jpa:
    hibernate:
      dialect: MySQL8Dialect
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbname: tingeso_1_2023
    url: jdbc:mysql://localhost:3306/tingeso_1_2023
    username: root
    password: 1234

