version: "3.8"
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tingeso_1_2023
    ports:
      - 33060:3306
  app:
    container_name: pep1
    image: nait0u/pep1
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/tingeso_1_2023?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
